<header id="header">
  <div>
    <button id="ham">
      <span></span>
      <span></span>
      <span></span>
    </button>
    <div id="hammenu">
      <ul>
        <li>
          <a href="#">HOME</a>
        </li>
        <li>
          <a href=".s2">VOTE</a>
        </li>
        <li>
          <a href=".s3">BOARD</a>
        </li>
      </ul>
    </div>
  </div>
  
    <h1 id="logo">KIMNEMA</h1>
  
  <ul id="login">
    <li>
      <a href="login.php">로그인</a>
    </li>
    <li>
      <a href="signin.php">회원가입</a>
    </li>
  </ul>
</header>
